### PR TITLE
Show puzzle version in main menu

### PR DESCRIPTION
**Pull request by SpaceNerd24**
Added the puzzle version to the main menu above the Cosmic Reach version.

### CODE REVIEW

**Comment by Mr-Zombii** [comment]
Nice, ima add you in the credits & merge the PR

**Comment by Mr-Zombii** [comment]
Okay, you need to test your code before you commit, ima do my best to fix it.

**Comment by Mr-Zombii** [comment]
wait, it crashes, i comment & uncomment and its fixed?, How strange

**Comment by SpaceNerd24** [comment]
There’s an error? I couldn’t find any in my testing, Sorry.

**Comment by Mr-Zombii** [comment]
There was but it vanished after a moment.

**Comment by Mr-Zombii** [comment]
Merged fully

**Pull request merged**
